# Generated by Django 5.1.3 on 2024-11-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
