# Generated by Django 5.1.3 on 2024-11-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0003_profile_avatar_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_avatars'),
        ),
    ]
