# Generated by Django 5.1.5 on 2025-01-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourarea', '0003_profile_date_modified_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/background_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
