# Generated by Django 4.1.4 on 2024-11-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0010_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_link',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok_link',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitch_link',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
