# Generated by Django 5.1.5 on 2025-01-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourarea', '0011_group_event_post_group_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/background_images'),
        ),
    ]
