# Generated by Django 4.1.4 on 2024-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0011_profile_custom_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
