# Generated by Django 5.1.5 on 2025-01-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourarea', '0012_group_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/group_images'),
        ),
    ]
