# Generated by Django 4.1.4 on 2024-11-29 17:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0014_profile_books_interests_profile_general_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
