# Generated by Django 4.1.4 on 2024-11-29 21:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0015_profile_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='colour',
        ),
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
