# Generated by Django 4.1.4 on 2024-11-30 03:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0016_remove_profile_colour_profile_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
