# Generated by Django 4.1.4 on 2024-11-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0017_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
