# Generated by Django 4.1.4 on 2024-12-02 03:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0022_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_colour',
            field=colorfield.fields.ColorField(default='#F49AC1', image_field=None, max_length=25, samples=None),
        ),
    ]
