# Generated by Django 4.1.4 on 2024-12-02 03:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0025_remove_profile_favourite_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
