# Generated by Django 4.1.4 on 2024-12-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourArea', '0026_profile_favourite_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
